/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wirbel' at '23.08.16 19:01' with Gradle 2.14.1
 *
 * @author wirbel, @date 23.08.16 19:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
