/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'wirbel' at '23.08.16 19:01' with Gradle 2.14.1
 *
 * @author wirbel, @date 23.08.16 19:01
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
